homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 33.118011
  longitude: -96.645739
    # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 190
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
    api_password: Fonajowo1
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

#Ring Doorbell
ring:
  username: jerryness@gmail.com
  password: Fountain24CS

#Rachio Sprinkler
switch:
  - platform: rachio
    access_token: 4e7fe121-d252-4a51-80bc-a86b9304a312

#Roku
media_player:
  - platform: roku
    host: 10.93.96.147
    host: 10.93.96.148

climate:
  - platform: radiotherm
    host:
      - 10.93.96.132
      - 10.93.96.149

#Synology DSM
synologydsm:
  host: 10.93.96.113
  username: jness
  password: jness

#Linksys Router
device_tracker:
  - platform: linksys_smart
    host: 10.93.96.231

panel_iframe:
  router:
    title: 'Router'
    url: 'http://10.93.96.231'
    icon: mdi:router-wireless

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
